# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"         # для Vite сборки

# SPA-редирект: все пути отдаем index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Полезные заголовки (необязательно)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
